In [1]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

NOTEBOOK_DIR = Path.cwd() / "notebooks" if (Path.cwd() / "notebooks").exists() else Path.cwd()
sys.path.insert(0, str(NOTEBOOK_DIR))
from pipeline_helpers import ARTIFACT_DIR, DATA_PATH, SEED

print(f"Data: {DATA_PATH}")
print(f"Artifacts: {ARTIFACT_DIR}")
print(f"Reproducibility seed: {SEED}")
from pipeline_helpers import phase1
result = phase1()
print("Source shape and detected WB_CCKP_ climate column count:")
display(result["shape"])

Data: D:\4th Semester\DS4105 - Capstone Project in Data Science II\reburn\data\raw\europe_cereal_yield_climate_1990_2022.csv
Artifacts: D:\4th Semester\DS4105 - Capstone Project in Data Science II\reburn\artifacts\cereal_yield_pipeline
Reproducibility seed: 42
Source shape and detected WB_CCKP_ climate column count:

   rows  columns  climate_columns
0  3245       43               37

## Schema, memory, missingness, and duplicates

No missing values or duplicate keys are repaired silently. The tables below show the observed values.

In [2]:
display(result["dtype_table"])
display(result["memory_summary"])
display(result["memory_summary"])
display(result["memory_table"].sort_values("memory_bytes", ascending=False))
display(result["missing_table"].query("missing_count > 0"))
display(result["duplicate_table"])

                       dtype
AREA                     str
ITEM                     str
YEAR                   int64
YIELD                float64
AREA_HARVESTED       float64
PRODUCTION_QUANTITY  float64
WB_CCKP_CDD          float64
WB_CCKP_CDD65        float64
WB_CCKP_CSDI         float64
WB_CCKP_CWD          float64
WB_CCKP_FD           float64
WB_CCKP_HD30         float64
WB_CCKP_HD35         float64
WB_CCKP_HD40         float64
WB_CCKP_HD42         float64
WB_CCKP_HD45         float64
WB_CCKP_HD50         float64
WB_CCKP_HDD65        float64
WB_CCKP_HI35         float64
WB_CCKP_HI37         float64
WB_CCKP_HI39         float64
WB_CCKP_HI41         float64
WB_CCKP_HURS         float64
WB_CCKP_ID           float64
WB_CCKP_PR           float64
WB_CCKP_R20MM        float64
WB_CCKP_R50MM        float64
WB_CCKP_R95PTOT      float64
WB_CCKP_RX1DAY       float64
WB_CCKP_RX5DAY       float64
WB_CCKP_SD           float64
WB_CCKP_TAS          float64
WB_CCKP_TASMAX       float64
WB_CCKP_TASMIN       float64
WB_CCKP_TNN          float64
WB_CCKP_TR           float64
WB_CCKP_TR23         float64
WB_CCKP_TR26         float64
WB_CCKP_TR29         float64
WB_CCKP_TR32         float64
WB_CCKP_TX84RR       float64
WB_CCKP_TXX          float64
WB_CCKP_WSDI         float64

   total_memory_bytes  total_memory_mib
0             1433830          1.367407

   total_memory_bytes  total_memory_mib
0             1433830          1.367407

                     memory_bytes  memory_mib
AREA                       186638    0.177992
ITEM                       182700    0.174236
YEAR                        25960    0.024757
YIELD                       25960    0.024757
WB_CCKP_CDD65               25960    0.024757
AREA_HARVESTED              25960    0.024757
PRODUCTION_QUANTITY         25960    0.024757
WB_CCKP_CDD                 25960    0.024757
WB_CCKP_CWD                 25960    0.024757
WB_CCKP_CSDI                25960    0.024757
WB_CCKP_FD                  25960    0.024757
WB_CCKP_HD30                25960    0.024757
WB_CCKP_R95PTOT             25960    0.024757
WB_CCKP_HD35                25960    0.024757
WB_CCKP_HD40                25960    0.024757
WB_CCKP_HD42                25960    0.024757
WB_CCKP_HD45                25960    0.024757
WB_CCKP_HD50                25960    0.024757
WB_CCKP_HDD65               25960    0.024757
WB_CCKP_HI35                25960    0.024757
WB_CCKP_HI37                25960    0.024757
WB_CCKP_HI39                25960    0.024757
WB_CCKP_HI41                25960    0.024757
WB_CCKP_HURS                25960    0.024757
WB_CCKP_ID                  25960    0.024757
WB_CCKP_PR                  25960    0.024757
WB_CCKP_R20MM               25960    0.024757
WB_CCKP_R50MM               25960    0.024757
WB_CCKP_TR                  25960    0.024757
WB_CCKP_RX1DAY              25960    0.024757
WB_CCKP_RX5DAY              25960    0.024757
WB_CCKP_SD                  25960    0.024757
WB_CCKP_TAS                 25960    0.024757
WB_CCKP_TASMAX              25960    0.024757
WB_CCKP_TASMIN              25960    0.024757
WB_CCKP_TNN                 25960    0.024757
WB_CCKP_TR32                25960    0.024757
WB_CCKP_TR23                25960    0.024757
WB_CCKP_TR26                25960    0.024757
WB_CCKP_TR29                25960    0.024757
WB_CCKP_TXX                 25960    0.024757
WB_CCKP_TX84RR              25960    0.024757
WB_CCKP_WSDI                25960    0.024757
Index                         132    0.000126

Empty DataFrame
Columns: [missing_count]
Index: []

                               check  count
0                duplicate full rows      0
1  duplicate (AREA, ITEM, YEAR) keys      0

## Domain checks and statistical outlier flags

Nonpositive target/area/production rows are excluded as invalid if present. Group IQR and |z| > 4 flags are reported by country, crop, year, and measure; statistically unusual observations remain unless they are domain errors.

In [3]:
display(result["domain_table"])
print(f"Outlier-flagged measure observations: {len(result['outlier_table'])}")
display(result["outlier_counts"])
display(result["outlier_table"])
display(result["cleaned_shape"])

Outlier-flagged measure observations: 207

                column  negative_count  zero_count  nonpositive_count  minimum      maximum
0                YIELD               0           0                  0    500.0      13741.9
1       AREA_HARVESTED               0           0                  0     70.0   29354766.0
2  PRODUCTION_QUANTITY               0           0                  0    248.0  104233944.0

                       AREA          ITEM              measure  flagged_rows
0                   Albania        Barley  PRODUCTION_QUANTITY             2
1                   Albania        Barley                YIELD             1
2                   Albania  Maize (corn)       AREA_HARVESTED             2
3                   Albania         Wheat       AREA_HARVESTED             1
4                   Albania         Wheat  PRODUCTION_QUANTITY             2
5                   Austria        Barley  PRODUCTION_QUANTITY             1
6                   Belarus        Barley       AREA_HARVESTED             1
7                   Belarus        Barley  PRODUCTION_QUANTITY             3
8                   Belarus        Barley                YIELD             1
9                   Belgium        Barley  PRODUCTION_QUANTITY             1
10                  Belgium        Barley                YIELD             1
11                  Belgium         Wheat       AREA_HARVESTED             1
12                  Belgium         Wheat                YIELD             2
13   Bosnia and Herzegovina        Barley       AREA_HARVESTED             3
14   Bosnia and Herzegovina  Maize (corn)       AREA_HARVESTED             8
15   Bosnia and Herzegovina  Maize (corn)                YIELD             2
16   Bosnia and Herzegovina         Wheat                YIELD             1
17                 Bulgaria        Barley  PRODUCTION_QUANTITY             1
18                 Bulgaria  Maize (corn)       AREA_HARVESTED             1
19                 Bulgaria         Wheat       AREA_HARVESTED             1
20                  Croatia         Wheat       AREA_HARVESTED             1
21                  Croatia         Wheat  PRODUCTION_QUANTITY             1
22                  Czechia         Wheat       AREA_HARVESTED             4
23                  Denmark        Barley       AREA_HARVESTED             3
24                  Denmark        Barley  PRODUCTION_QUANTITY             2
25                  Denmark        Barley                YIELD             2
26                  Denmark         Wheat  PRODUCTION_QUANTITY             2
27                  Estonia        Barley       AREA_HARVESTED             3
28                  Finland        Barley                YIELD             4
29                  Finland         Wheat                YIELD             4
30                   France        Barley  PRODUCTION_QUANTITY             1
31                   France  Maize (corn)                YIELD             1
32                   France         Wheat       AREA_HARVESTED             4
33                   France         Wheat                YIELD             1
34                  Germany        Barley  PRODUCTION_QUANTITY             1
35                  Germany  Maize (corn)  PRODUCTION_QUANTITY             1
36                   Greece        Barley                YIELD             1
37                   Greece  Maize (corn)                YIELD             2
38                   Greece         Wheat  PRODUCTION_QUANTITY             1
39                  Hungary        Barley       AREA_HARVESTED             1
40                  Hungary  Maize (corn)       AREA_HARVESTED             1
41                  Hungary         Wheat       AREA_HARVESTED             1
42                  Iceland        Barley  PRODUCTION_QUANTITY             2
43                  Iceland        Barley                YIELD             1
44                  Ireland        Barley       AREA_HARVESTED             2
45                    Italy        Barley  PRODUCTION_QUANTITY             1
46                    Italy        Barley                YIELD             3
47                   Latvia        Barley       AREA_HARVESTED             3
48               Luxembourg        Barley                YIELD             1
49               Luxembourg         Wheat  PRODUCTION_QUANTITY             1
50                    Malta        Barley       AREA_HARVESTED             5
51                    Malta        Barley  PRODUCTION_QUANTITY             4
52                    Malta         Wheat       AREA_HARVESTED             3
53                  Moldova        Barley  PRODUCTION_QUANTITY             2
54                  Moldova  Maize (corn)       AREA_HARVESTED             3
55                  Moldova  Maize (corn)  PRODUCTION_QUANTITY             2
56                  Moldova  Maize (corn)                YIELD             1
57                  Moldova         Wheat       AREA_HARVESTED             1
58                  Moldova         Wheat                YIELD             1
59               Montenegro        Barley       AREA_HARVESTED             1
60               Montenegro        Barley  PRODUCTION_QUANTITY             2
61               Montenegro        Barley                YIELD             1
62               Montenegro  Maize (corn)       AREA_HARVESTED             5
63               Montenegro  Maize (corn)  PRODUCTION_QUANTITY             1
64               Montenegro  Maize (corn)                YIELD             3
65              Netherlands        Barley       AREA_HARVESTED             1
66          North Macedonia  Maize (corn)  PRODUCTION_QUANTITY             2
67          North Macedonia  Maize (corn)                YIELD             1
68                   Norway         Wheat                YIELD             3
69                   Poland        Barley       AREA_HARVESTED             2
70                   Poland        Barley                YIELD             2
71                   Poland         Wheat  PRODUCTION_QUANTITY             3
72                  Romania        Barley       AREA_HARVESTED             3
73                  Romania        Barley  PRODUCTION_QUANTITY             1
74                  Romania  Maize (corn)  PRODUCTION_QUANTITY             2
75                  Romania  Maize (corn)                YIELD             2
76                  Romania         Wheat       AREA_HARVESTED             5
77       Russian Federation        Barley       AREA_HARVESTED             5
78       Russian Federation        Barley  PRODUCTION_QUANTITY             1
79       Russian Federation         Wheat  PRODUCTION_QUANTITY             1
80       Russian Federation         Wheat                YIELD             1
81                   Serbia        Barley       AREA_HARVESTED             4
82                   Serbia        Barley                YIELD             1
83                   Serbia         Wheat       AREA_HARVESTED             1
84                   Serbia         Wheat                YIELD             1
85          Slovak Republic         Wheat       AREA_HARVESTED             1
86                 Slovenia  Maize (corn)       AREA_HARVESTED             2
87                 Slovenia  Maize (corn)                YIELD             1
88                    Spain  Maize (corn)  PRODUCTION_QUANTITY             1
89                   Sweden        Barley  PRODUCTION_QUANTITY             6
90                   Sweden  Maize (corn)       AREA_HARVESTED             1
91                   Sweden  Maize (corn)  PRODUCTION_QUANTITY             2
92                   Sweden  Maize (corn)                YIELD             2
93                   Sweden         Wheat  PRODUCTION_QUANTITY             6
94                   Sweden         Wheat                YIELD             4
95              Switzerland  Maize (corn)                YIELD             1
96              Switzerland         Wheat  PRODUCTION_QUANTITY             2
97              Switzerland         Wheat                YIELD             1
98                  Ukraine         Wheat       AREA_HARVESTED             1
99           United Kingdom        Barley       AREA_HARVESTED             1
100          United Kingdom        Barley                YIELD             3
101          United Kingdom         Wheat       AREA_HARVESTED             1
102          United Kingdom         Wheat  PRODUCTION_QUANTITY             2

                       AREA          ITEM  YEAR              measure        value  group_z_score  group_lower_iqr  group_upper_iqr  iqr_flag  z_gt_4_flag                                                                              review
0                   Albania        Barley  2002                YIELD       4750.0       2.893895     3.329000e+02     4.434500e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
1                   Belarus        Barley  2022                YIELD       4524.9       2.665400     1.273825e+03     4.368025e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
2                   Belgium        Barley  2008                YIELD       6000.1      -2.186457     6.197025e+03     9.654425e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
3                   Belgium         Wheat  2015                YIELD      10015.2       2.093028     7.215075e+03     1.001248e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
4                   Belgium         Wheat  2016                YIELD       6787.1      -2.640089     7.215075e+03     1.001248e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
5    Bosnia and Herzegovina  Maize (corn)  2020                YIELD       7112.4       1.931638     2.232425e+03     6.794625e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
6    Bosnia and Herzegovina  Maize (corn)  2022                YIELD       8540.0       3.015685     2.232425e+03     6.794625e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
7    Bosnia and Herzegovina         Wheat  2022                YIELD       5460.0       2.832360     1.884400e+03     4.960800e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
8                   Denmark        Barley  1992                YIELD       3266.4      -3.333418     4.203100e+03     6.455100e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
9                   Denmark        Barley  2022                YIELD       6708.9       2.168480     4.203100e+03     6.455100e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
10                  Finland        Barley  1998                YIELD       2276.8      -2.933199     2.733750e+03     4.213350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
11                  Finland        Barley  1999                YIELD       2698.3      -1.878271     2.733750e+03     4.213350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
12                  Finland        Barley  2019                YIELD       4277.4       2.073891     2.733750e+03     4.213350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
13                  Finland        Barley  2021                YIELD       2694.9      -1.886781     2.733750e+03     4.213350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
14                  Finland         Wheat  1992                YIELD       2415.2      -2.409181     2.864150e+03     4.436550e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
15                  Finland         Wheat  1999                YIELD       2158.9      -2.928788     2.864150e+03     4.436550e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
16                  Finland         Wheat  2018                YIELD       2821.1      -1.586283     2.864150e+03     4.436550e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
17                  Finland         Wheat  2019                YIELD       4626.4       2.073674     2.864150e+03     4.436550e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
18                   France  Maize (corn)  1990                YIELD       6018.6      -2.858867     6.616150e+03     1.043415e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
19                   France         Wheat  2016                YIELD       5289.6      -3.159244     5.691300e+03     8.191300e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
20                   Greece        Barley  1990                YIELD       1743.0      -3.318673     1.884950e+03     3.293350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
21                   Greece  Maize (corn)  1998                YIELD       8824.7      -2.526966     8.995350e+03     1.161095e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
22                   Greece  Maize (corn)  2015                YIELD      11670.2       2.221639     8.995350e+03     1.161095e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
23                  Iceland        Barley  2020                YIELD       4858.0       2.195670     2.394825e+03     4.228025e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
24                    Italy        Barley  2020                YIELD       4265.8       1.852056     3.278000e+03     4.236400e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
25                    Italy        Barley  2021                YIELD       4337.3       2.121443     3.278000e+03     4.236400e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
26                    Italy        Barley  2022                YIELD       4323.1       2.067942     3.278000e+03     4.236400e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
27               Luxembourg        Barley  2001                YIELD       4609.0      -2.032900     4.625200e+03     6.249200e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
28               Montenegro        Barley  2007                YIELD       1203.9      -3.455705     2.241800e+03     3.125000e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
29               Montenegro  Maize (corn)  2007                YIELD       2500.0      -2.351557     3.048750e+03     5.038750e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
30               Montenegro  Maize (corn)  2013                YIELD       5177.5       1.703105     3.048750e+03     5.038750e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
31               Montenegro  Maize (corn)  2014                YIELD       5084.6       1.562422     3.048750e+03     5.038750e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
32          North Macedonia  Maize (corn)  1993                YIELD       2261.3      -3.036265     2.956300e+03     5.400300e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
33                   Norway         Wheat  1994                YIELD       2836.2      -2.265786     3.102550e+03     5.765350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
34                   Norway         Wheat  2015                YIELD       5774.5       1.892125     3.102550e+03     5.765350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
35                   Norway         Wheat  2018                YIELD       2347.7      -2.957050     3.102550e+03     5.765350e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
36                   Poland        Barley  2020                YIELD       4359.5       2.089949     2.298350e+03     4.345150e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
37                   Poland        Barley  2022                YIELD       4352.1       2.075091     2.298350e+03     4.345150e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
38                  Moldova  Maize (corn)  2021                YIELD       5742.5       3.121248     1.152625e+03     4.750425e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
39                  Moldova         Wheat  2021                YIELD       4601.4       2.649072     9.514500e+02     4.556650e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
40                  Romania  Maize (corn)  2018                YIELD       7636.8       2.937153     1.128850e+03     6.230850e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
41                  Romania  Maize (corn)  2019                YIELD       6499.9       2.076897     1.128850e+03     6.230850e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
42       Russian Federation         Wheat  2022                YIELD       3550.8       2.611259     7.151250e+02     3.525725e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
43                   Serbia        Barley  2021                YIELD       5623.9       2.496226     2.618500e+03     4.822500e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
44                   Serbia         Wheat  2021                YIELD       5749.3       2.366003     3.007200e+03     5.514400e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
45                 Slovenia  Maize (corn)  1992                YIELD       2815.0      -2.611184     2.903750e+03     1.203775e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
46                   Sweden  Maize (corn)  2018                YIELD       4144.1      -1.586188     6.429050e+03     7.303050e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
47                   Sweden  Maize (corn)  2021                YIELD       8563.2       1.192811     6.429050e+03     7.303050e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
48                   Sweden         Wheat  2015                YIELD       7213.2       1.779633     4.967400e+03     7.132200e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
49                   Sweden         Wheat  2018                YIELD       4349.8      -2.708969     4.967400e+03     7.132200e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
50                   Sweden         Wheat  2019                YIELD       7405.5       2.081078     4.967400e+03     7.132200e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
51                   Sweden         Wheat  2020                YIELD       7156.1       1.690124     4.967400e+03     7.132200e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
52              Switzerland  Maize (corn)  2003                YIELD       4299.0      -3.839574     6.182750e+03     1.256155e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
53              Switzerland         Wheat  2016                YIELD       4370.5      -3.276826     4.776900e+03     6.736100e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
54           United Kingdom        Barley  2015                YIELD       6693.9       2.152316     5.034450e+03     6.494050e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
55           United Kingdom        Barley  2019                YIELD       6926.0       2.723851     5.034450e+03     6.494050e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
56           United Kingdom        Barley  2022                YIELD       6689.3       2.140989     5.034450e+03     6.494050e+03      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
57                  Albania  Maize (corn)  1993       AREA_HARVESTED      72669.0       2.286565     3.720800e+04     7.132000e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
58                  Albania  Maize (corn)  1994       AREA_HARVESTED      74767.0       2.572035     3.720800e+04     7.132000e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
59                  Albania         Wheat  1990       AREA_HARVESTED     203000.0       2.890810     6.995000e+03     1.750030e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
60                  Belarus        Barley  1994       AREA_HARVESTED    1267000.0       2.549784     1.325400e+05     1.173276e+06      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
61                  Belgium         Wheat  2001       AREA_HARVESTED     181100.0      -2.690003     1.852860e+05     2.254700e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
62   Bosnia and Herzegovina        Barley  1994       AREA_HARVESTED      17000.0      -2.002997     1.730575e+04     2.562775e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
63   Bosnia and Herzegovina        Barley  1995       AREA_HARVESTED      16200.0      -2.392236     1.730575e+04     2.562775e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
64   Bosnia and Herzegovina        Barley  2016       AREA_HARVESTED      25631.0       2.196408     1.730575e+04     2.562775e+04      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
65   Bosnia and Herzegovina  Maize (corn)  1992       AREA_HARVESTED     158000.0      -0.824940     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
66   Bosnia and Herzegovina  Maize (corn)  1993       AREA_HARVESTED     135000.0      -1.572310     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
67   Bosnia and Herzegovina  Maize (corn)  1994       AREA_HARVESTED     115000.0      -2.222197     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
68   Bosnia and Herzegovina  Maize (corn)  1995       AREA_HARVESTED      93000.0      -2.937072     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
69   Bosnia and Herzegovina  Maize (corn)  1996       AREA_HARVESTED     147000.0      -1.182378     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
70   Bosnia and Herzegovina  Maize (corn)  1998       AREA_HARVESTED     219104.0       1.160594     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
71   Bosnia and Herzegovina  Maize (corn)  2014       AREA_HARVESTED     169948.0      -0.436698     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
72   Bosnia and Herzegovina  Maize (corn)  2022       AREA_HARVESTED     115599.0      -2.202733     1.727158e+05     2.153938e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
73                 Bulgaria  Maize (corn)  2007       AREA_HARVESTED     214367.0      -2.315975     2.182980e+05     6.580820e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
74                 Bulgaria         Wheat  2003       AREA_HARVESTED     841014.0      -2.621926     9.472100e+05     1.370426e+06      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
75                  Croatia         Wheat  1998       AREA_HARVESTED     241734.0       2.481621     1.040028e+05     2.345768e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
76                  Czechia         Wheat  1998       AREA_HARVESTED     912301.0       1.530745     7.573106e+05     9.000936e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
77                  Czechia         Wheat  2000       AREA_HARVESTED     970435.0       2.612801     7.573106e+05     9.000936e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
78                  Czechia         Wheat  2001       AREA_HARVESTED     923236.0       1.734279     7.573106e+05     9.000936e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
79                  Czechia         Wheat  2003       AREA_HARVESTED     648390.0      -3.381470     7.573106e+05     9.000936e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
80                  Denmark        Barley  1990       AREA_HARVESTED     901115.0       2.177042     4.867500e+05     8.727500e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
81                  Denmark        Barley  1991       AREA_HARVESTED     938577.0       2.593088     4.867500e+05     8.727500e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.
82                  Denmark        Barley  1992       AREA_HARVESTED     910392.0       2.280071     4.867500e+05     8.727500e+05      True        False  Retained pending domain review; statistical extremeness alone is not a data error.

   rows_before  rows_after  removed_nonpositive_rows
0         3245        3245                         0

## Yield distribution and year coverage

Yield is in the source dataset’s reported units. Crop labels are preserved exactly as stored (including `Maize (corn)`). Coverage below includes every observed country × crop pair, including pairs with no rows.

In [4]:
display(result["overall_yield"])
display(result["crop_yield"])
display(result["country_yield"])
coverage = result["coverage_table"]
print(f"Country × crop combinations possible from observed labels: {len(coverage)}")
print(f"Combinations with at least one observed year: {(coverage['observed_years'] > 0).sum()}")
print(f"Combinations with no rows at all: {(coverage['observed_years'] == 0).sum()}")
print(f"Combinations with one or more year gaps: {(coverage['missing_year_count'] > 0).sum()}")
display(coverage.loc[coverage["missing_year_count"] > 0])
crop_stats = result["crop_yield"].set_index("ITEM")
maize = crop_stats.loc["Maize (corn)"]
print(f"Maize (corn): n={int(maize['count'])}, mean={maize['mean']:.1f}, std={maize['std']:.1f}; compare with Barley and Wheat in the table above.")
print(f"Country row counts range from {int(result['country_yield']['row_count'].min())} to {int(result['country_yield']['row_count'].max())}; yields also vary materially by country, so AREA and ITEM are retained as context features.")
print("The source does not provide separate unit metadata by crop or country.")

Country × crop combinations possible from observed labels: 117
Combinations with at least one observed year: 108
Combinations with no rows at all: 9
Combinations with one or more year gaps: 63
Maize (corn): n=899, mean=6558.3, std=2721.6; compare with Barley and Wheat in the table above.
Country row counts range from 8 to 99; yields also vary materially by country, so AREA and ITEM are retained as context features.
The source does not provide separate unit metadata by crop or country.

        count         mean  median          std    min      max
YIELD  3245.0  4878.708105  4249.2  2361.701809  500.0  13741.9

           ITEM  count         mean  median          std    min      max
0        Barley   1177  3900.403314  3592.0  1612.165722  720.5   9145.7
1  Maize (corn)    899  6558.297887  6444.6  2721.583066  500.0  13741.9
2         Wheat   1169  4572.047305  4107.3  1987.400053  664.4  10667.7

                      AREA  count         mean   median          std     min      max  row_count
0                  Belgium     69  8982.079710  8577.00  1631.986977  6000.1  13127.8         69
1              Netherlands     99  8144.766667  8015.40  1912.923085  5039.4  13741.9         99
2                  Ireland     66  7815.225758  7872.70  1354.465511  5298.7  10667.7         66
3                  Germany     99  7394.104040  7234.80  1390.203551  5000.8  10683.8         99
4                   France     99  7215.418182  6988.70  1191.757959  5205.9  10123.9         99
5              Switzerland     99  7100.710101  6295.20  1805.702080  4299.0  11444.7         99
6           United Kingdom     66  6786.556061  6756.65  1090.363336  5187.3   8976.0         66
7                  Austria     99  6622.650505  5606.40  2327.442220  3819.5  11344.9         99
8                  Denmark     79  6341.283544  6248.40  1108.374943  3266.4   8376.0         79
9               Luxembourg     69  6198.185507  5948.80  1197.477833  4609.0  10800.0         69
10                 Czechia     90  5539.965556  5364.65  1525.783153  3293.4   9788.2         90
11                   Italy     99  5527.470707  3868.90  2699.640053  2748.2  11268.2         99
12                Slovenia     93  5341.529032  4807.70  1832.336326  2815.0  10792.1         93
13                  Sweden     71  5303.987324  5340.30  1169.373633  2919.0   8563.2         71
14                  Greece     99  5170.095960  2776.90  3695.721774  1743.0  11670.2         99
15                   Spain     99  5133.654545  3252.40  3515.410436  1419.2  12832.9         99
16                 Croatia     93  4930.761290  4640.80  1480.029497  2464.6   9123.8         93
17                 Hungary     99  4761.365657  4448.10  1427.159745  2377.4   8630.1         99
18         Slovak Republic     90  4738.257778  4576.55  1430.833584  1990.1   9253.7         90
19                  Serbia     51  4581.660784  4259.20  1297.597040  2759.9   7900.0         51
20                  Poland     99  4390.888889  4051.60  1298.122238  2353.1   7348.1         99
21                  Norway     66  4089.433333  4157.05   697.785523  2347.7   5774.5         66
22                Bulgaria     99  3890.988889  3759.60  1316.062443  1723.9   7922.5         99
23                   Malta     56  3887.910714  4000.00   780.133585  2000.0   5031.1         56
24  Bosnia and Herzegovina     93  3688.094624  3526.30  1122.742396  1903.0   8540.0         93
25                 Albania     99  3608.206061  3130.00  1547.609155   923.1   7227.3         99
26                 Finland     66  3526.157576  3554.05   452.166099  2158.9   4626.4         66
27               Lithuania     93  3488.998925  3159.80  1590.524762  1000.0   7671.9         93
28                 Ukraine     93  3440.702151  3092.60  1378.398667  1462.9   7843.9         93
29                 Iceland      8  3382.450000  3199.70   672.027185  2600.0   4858.0          8
30                Portugal     99  3325.155556  2208.80  2560.834950   664.4  10104.6         99
31                 Belarus     93  3281.361290  3061.00  1153.389355   500.0   6595.0         93
32                 Romania     99  3263.193939  3118.10  1070.481567  1568.9   7636.8         99
33         North Macedonia     93  3244.689247  3150.90   801.439981  1788.7   5145.6         93
34              Montenegro     51  3237.013725  3046.30   775.917835  1203.9   5177.5         51
35                  Latvia     62  2928.917742  2731.95   974.352220  1237.2   5338.4         62
36                 Estonia     62  2785.554839  2526.45   994.119920  1121.4   5069.9         62
37                 Moldova     93  2654.811828  2637.60   842.404337   720.5   5742.5         93
38      Russian Federation     93  2594.510753  2228.80  1124.692513  1073.2   5998.9         93

                       AREA          ITEM  observed_years  expected_years  missing_year_count                                                                                                                                                                                         missing_years
6                   Belarus        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
7                   Belarus  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
8                   Belarus         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
9                   Belgium        Barley              23              33                  10                                                                                                                                            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999
10                  Belgium  Maize (corn)              23              33                  10                                                                                                                                            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999
11                  Belgium         Wheat              23              33                  10                                                                                                                                            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999
12   Bosnia and Herzegovina        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
13   Bosnia and Herzegovina  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
14   Bosnia and Herzegovina         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
18                  Croatia        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
19                  Croatia  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
20                  Croatia         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
21                  Czechia        Barley              30              33                   3                                                                                                                                                                                      1990, 1991, 1992
22                  Czechia  Maize (corn)              30              33                   3                                                                                                                                                                                      1990, 1991, 1992
23                  Czechia         Wheat              30              33                   3                                                                                                                                                                                      1990, 1991, 1992
25                  Denmark  Maize (corn)              13              33                  20                                                                                1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009
27                  Estonia        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
28                  Estonia  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
29                  Estonia         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
31                  Finland  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
45                  Iceland        Barley               8              33                  25                                                  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014
46                  Iceland  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
47                  Iceland         Wheat               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
49                  Ireland  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
54                   Latvia        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
55                   Latvia  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
56                   Latvia         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
57                Lithuania        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
58                Lithuania  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
59                Lithuania         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
60               Luxembourg        Barley              23              33                  10                                                                                                                                            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999
61               Luxembourg  Maize (corn)              23              33                  10                                                                                                                                            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999
62               Luxembourg         Wheat              23              33                  10                                                                                                                                            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999
63                    Malta        Barley              28              33                   5                                                                                                                                                                          2018, 2019, 2020, 2021, 2022
64                    Malta  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
65                    Malta         Wheat              28              33                   5                                                                                                                                                                          2018, 2019, 2020, 2021, 2022
66                  Moldova        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
67                  Moldova  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
68                  Moldova         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
69               Montenegro        Barley              17              33                  16                                                                                                        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005
70               Montenegro  Maize (corn)              17              33                  16                                                                                                        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005
71               Montenegro         Wheat              17              33                  16                                                                                                        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005
75          North Macedonia        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
76          North Macedonia  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
77          North Macedonia         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
79                   Norway  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022
90       Russian Federation        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
91       Russian Federation  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
92       Russian Federation         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
93                   Serbia        Barley              17              33                  16                                                                                                        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005
94                   Serbia  Maize (corn)              17              33                  16                                                                                                        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005
95                   Serbia         Wheat              17              33                  16                                                                                                        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005
96          Slovak Republic        Barley              30              33                   3                                                                                                                                                                                      1990, 1991, 1992
97          Slovak Republic  Maize (corn)              30              33                   3                                                                                                                                                                                      1990, 1991, 1992
98          Slovak Republic         Wheat              30              33                   3                                                                                                                                                                                      1990, 1991, 1992
99                 Slovenia        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
100                Slovenia  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
101                Slovenia         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
106                  Sweden  Maize (corn)               5              33                  28                                1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017
111                 Ukraine        Barley              31              33                   2                                                                                                                                                                                            1990, 1991
112                 Ukraine  Maize (corn)              31              33                   2                                                                                                                                                                                            1990, 1991
113                 Ukraine         Wheat              31              33                   2                                                                                                                                                                                            1990, 1991
115          United Kingdom  Maize (corn)               0              33                  33  1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022

### Phase 1 output

The cleaned table is saved to `artifacts/cereal_yield_pipeline/phase1_cleaned.pkl`. Only nonpositive domain-invalid rows are removed; all statistical outlier flags are retained for review.